#pragma once

#define IDD_GPIODLG		101
#define	IDD_USARTDLG	102

#define IDC_LABEL		-1
#define IDC_GRP		-1

#define GPIOID_PORT_CB		121
#define GPIOID_PIN_GRP_CB	122
#define GPIOID_PIN_CB		123
#define GPIOID_SETAS_CB		125
#define GPIOID_CONFIG_CB	126
#define GPIOID_OUTMODE_CB	127
#define GPIOID_SET_PIN_BTN	128
#define GPIOID_READ_EDT		130
#define GPIOID_READ_BTN		131
#define GPIOID_WRITE_EDT	133
#define GPIOID_WRITE_BTN	134

#define USARTID_BAUD_CB			141
#define USARTID_DATABITS_CB		142
#define USARTID_PARITY_CB		143
#define USARTID_STOPBIT_CB		144
#define USARTID_FLOWCTL_CB		145
#define USARTID_NO_CB			146
#define USARTID_OPEN_BTN		147
#define	USARTID_CLOSE_BTN		148
#define USARTID_READ_EDT		149
#define USARTID_READ_BTN		150
#define USARTID_READ_LEN_EDT	151
#define USARTID_WRITE_EDT		154
#define USARTID_WRITE_BTN		155
