/*
 * File    : Address.h
 * Remark  : The definition of addresses of NanoOS
 *
 */

#ifndef ADDRESS_H
#define ADDRESS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "Thread.h"

#define FLASH_ADDRESS				0x00000000				// Could be mapped by hardware
#define FLASH_SIZE					0x00010000				// 64 KB

#define SRAM_ADDRESS				0x20000000
#define SRAM_SIZE					0x00005000				// 20 KB

#define FLASH_WRITE_BASE_ADDRESS	0x08000000
#define FLASH_PAGE_OFFSET			0x00000400				// 1 KB
#define FLASH_PAGE_SIZE				FLASH_PAGE_OFFSET		// 1 KB

#define CONFIG_ADDRESS				0x0000FC00
#define CONFIG_SIZE					FLASH_PAGE_SIZE			// 1 KB
#define CONFIG_WRITE_ADDRESS		(FLASH_WRITE_BASE_ADDRESS + CONFIG_ADDRESS)		// 0x0800FC00

#define SYSTEM_FLASH_ADDRESS		FLASH_ADDRESS
#define SYSTEM_FLASH_SIZE			(FLASH_SIZE / 2)					// 32 KB

#define SYSTEM_SRAM_SIZE			(SRAM_SIZE / 2)						// 10 KB
#define SYSTEM_SRAM_ADDRESS			(SRAM_ADDRESS + (SRAM_SIZE / 2))	// 0x20002800
#define SYSTEM_STACK_ADDRESS		(SYSTEM_SRAM_ADDRESS + SYSTEM_SRAM_SIZE)
#define SYSTEM_START_STACK_ADDRESS	(SYSTEM_STACK_ADDRESS - 4)

#define APP_SRAM_ADDRESS			0x20000000
#define APP_SRAM_SIZE				0x00002800							// 10240 B = 10 KB
#define APP_STACK_SIZE				(THREAD_STACK_SIZE * STACK_ALIGN)

#define APP_FLASH_SIZE				((FLASH_SIZE / 2) - 1024)			// 31 KB
#define APP_FLASH_ADDRESS			(FLASH_ADDRESS + SYSTEM_FLASH_SIZE)	// 0x00008000
#define APP_FLASH_RUN_ADDRESS		(APP_FLASH_ADDRESS + 1)
#define APP_FLASH_WRITE_ADDRESS		(FLASH_WRITE_BASE_ADDRESS + APP_FLASH_ADDRESS)	// 0x08008000

#ifdef __cplusplus
}
#endif

#endif  // End of ADDRESS_H
